# CLI.
gfcli:
  gen:
    dao:
      - link:            "mysql:root:KY1234@tcp(localhost:3306)/xhr?charset=utf8mb4&parseTime=true&loc=Local"
        tables:          "t_department,t_nurse,t_title"
        removePrefix:    "t_"
        descriptionTag:  true
        noModelComment:  true
        path: "./internal/app/demo"